image: gradle:7.5.1-jdk8

stages:
  - build
  
build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - BornesEar/build/libs
      - BornesEjb/build/libs
      - BornesWeb/build/libs
  only:
    - master
    - develop